# Generated by Django 6.0.3 on 2026-04-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emergencyalert_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='peer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
