services:
  - type: web
    name: crisis-backend
    env: python
    region: ohio
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python crisis_backend/manage.py migrate
      python crisis_backend/manage.py collectstatic --noinput
    startCommand: gunicorn crisis_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        fromEnv: SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        fromEnv: ALLOWED_HOSTS
      - key: DJANGO_SETTINGS_MODULE
        value: crisis_backend.settings

  - type: static
    name: crisis-frontend
    buildCommand: |
      cd crisis_frontend
      npm install
      npm run build
    staticPublishPath: crisis_frontend/dist
    routes:
      - path: /api
        destination: crisis-backend
      - path: /media
        destination: crisis-backend
