# Generated by Django 6.0.4 on 2026-04-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emergencyalert_peer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='image',
        ),
        migrations.AddField(
            model_name='incident',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
